### ISSUE TITLE
Didn't find class "com.bumptech.glide.Glide"

### ISSUE THREAD

**Issue by dev-satinderpal** [mieszko4/react-native-zoom-us-test#39]
I'm getting an issue on android on application startup but this is working fine on iOS.
Here are the android studio logs:

--------- beginning of crash
**2022-03-05 12:32:56.546 15474-15474/com.zoomustest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zoomustest, PID: 15474
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/Glide;
        at us.zoom.sdk.ZoomSDK.initialize(ZoomSDK.java:93)
        at ch.milosz.reactnative.RNZoomUsModule$2.run(RNZoomUsModule.java:163)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8019)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bumptech.glide.Glide" on path: DexPathList[[zip file "/data/app/~~uAxrddS0f2_K2QblEg5JfQ==/com.zoomustest-XLy69CLWaVajllgLiBv4ew==/base.apk"],nativeLibraryDirectories=[/data/app/~~uAxrddS0f2_K2QblEg5JfQ==/com.zoomustest-XLy69CLWaVajllgLiBv4ew==/lib/arm64, /data/app/~~uAxrddS0f2_K2QblEg5JfQ==/com.zoomustest-XLy69CLWaVajllgLiBv4ew==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at us.zoom.sdk.ZoomSDK.initialize(ZoomSDK.java:93) 
        at ch.milosz.reactnative.RNZoomUsModule$2.run(RNZoomUsModule.java:163) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:236) 
        at android.app.ActivityThread.main(ActivityThread.java:8019) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)** 
2022-03-05 12:32:56.550 15474-15474/com.zoomustest D/OOMEventManagerFK: checkEventAndDumpForJE: 0
2022-03-05 12:32:56.589 15474-15474/com.zoomustest I/Process: Sending signal. PID: 15474 SIG: 9

**Comment by dev-satinderpal** [comment]
Issue resolved by adding below code in App level build.gradle file

dependencies {
...
     implementation 'com.github.bumptech.glide:glide:4.8.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'
...
}

**Comment by mieszko4** [comment]
The fix for "glide" was added in 6.7.1. Could you try to update to `react-native-zoom-us@6.7.1` and check if the issue still shows for you?

**Comment by mieszko4** [comment]
I've created an issue to myself to update and test the lib https://github.com/mieszko4/react-native-zoom-us-test/issues/41

**Comment by mieszko4** [comment]
Tested on `6.9.0`
